#!/bin/bash
# Masking-KD: distill Qwen3-VL-8B-Thinking (teacher) into Qwen3-VL-2B-Thinking (student).
# Global batch size = num GPUs x 1 (per device) x gradient accumulation steps = 512.
set -e

export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1}
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
NUM_GPUS=$(echo "$CUDA_VISIBLE_DEVICES" | tr ',' '\n' | wc -l)
GLOBAL_BATCH_SIZE=512

STUDENT_MODEL="Qwen/Qwen3-VL-2B-Thinking"
TEACHER_MODEL="Qwen/Qwen3-VL-8B-Thinking"
# Released teacher rollouts. To use rollouts generated by scripts/generate_rollouts.sh instead,
# set DATA_PATH="./data/rollouts/qwen3_vl_8b_thinking_correct".
DATA_PATH="SeonghoonYu/Masking-KD-Rollouts"
OUTPUT_DIR="./checkpoints/masking_kd_qwen3_vl_2b_thinking"

accelerate launch \
    --num_processes "$NUM_GPUS" \
    --use_deepspeed \
    --deepspeed_config_file configs/zero2.json \
    train.py \
    --student_model_name_or_path "$STUDENT_MODEL" \
    --teacher_model_name_or_path "$TEACHER_MODEL" \
    --data_path "$DATA_PATH" \
    --output_dir "$OUTPUT_DIR" \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps $((GLOBAL_BATCH_SIZE / NUM_GPUS)) \
    --learning_rate 1e-6 \
    --warmup_ratio 0.03 \
    --weight_decay 0.01 \
    --bf16 True \
    --gradient_checkpointing True \
    --logging_steps 1 \
    --save_strategy epoch \
    --save_total_limit 2 \
    --report_to none \
    --dataloader_num_workers 4 \
    --tau_min 0.3 \
    --tau_max 0.5 \
    --sigmoid_scale 1.0 \
    --max_mask_ratio 0.3 \
    --min_mask_k 1 \
    --fallback_mask_ratio 0.1 \
    --resp_attn_min 0.10 \
    --max_seq_len 5000 \
    --kl_chunk_size 512
